[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
    "B008",
    "C901",
    "E402",
    "F401",
    "W291",
    "I001",
    "F841",
    "W605",
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["B011"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.isort]
known-first-party = ["app", "config", "theme", "translations", "utils", "installer", "pages"]
